USE blood_bank;
ALTER TABLE Users ADD COLUMN last_login TIMESTAMP NULL;
ALTER TABLE Users ADD COLUMN email VARCHAR(100) NULL;
ALTER TABLE Users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
DESCRIBE Users;
